#!/usr/bin/env bash
git clone --bare git@github.com:mrichards42/dotfiles.git $HOME/.dotfiles || exit 1

# This is added as an alias in .bashrc
function dotfiles {
   /usr/bin/env git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

if ! dotfiles checkout; then
  BACKUP="$HOME/dotfiles-backup-$(date +'%Y%m%d%H%M%S')"
  echo "Backing up existing dotfiles to $BACKUP"
  dotfiles checkout 2>&1 | egrep '^\s+' | while read filename; do
    mkdir -p $(dirname "$BACKUP/$filename") &&
      mv "$HOME/$filename" "$BACKUP/$filename" &&
      echo "$HOME/$filename -> $BACKUP/$filename"
  done
  dotfiles checkout || exit 1;
fi

dotfiles config status.showUntrackedFiles no
echo "Use dotfiles alias instead of git for this repo."

